services:
  # A Docker web service
  - type: web
    name: langgraph-example
    env: docker
    plan: free
    region: oregon
    branch: main
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "langgraph-example"