services:
  # A Docker web service
  - type: web
    name: ai-research-agent
    env: docker
    plan: free
    region: oregon
    branch: main
    numInstances: 1
    healthCheckPath: /health
    # Explicitly set the port that the service runs on
    envVars:
      - key: PORT
        value: 8000
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: METAPHOR_API_KEY
        sync: false
      - key: BROWSERLESS_API_KEY
        sync: false
      - key: APIFY_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "ai-research-agent"